BDDMBundle\Entity\Action:
    type: entity
    table: null
    repositoryClass: BDDMBundle\Repository\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        type:
            type: string
            length: 255
        dateDebut:
            type: string
            length: 255
            column: date_debut
        duree:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
    lifecycleCallbacks: {  }
