BDDMBundle\Entity\Formation:
    type: entity
    table: null
    repositoryClass: BDDMBundle\Repository\FormationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateDebut:
            type: string
            length: 255
            column: date_debut
        duree:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        type:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
