association_index:
    path:     /
    defaults: { _controller: "FaucheurBundle:Association:index" }
    methods:  GET

association_show:
    path:     /{id}/show
    defaults: { _controller: "FaucheurBundle:Association:show" }
    methods:  GET

association_new:
    path:     /new
    defaults: { _controller: "FaucheurBundle:Association:new" }
    methods:  [GET, POST]

association_edit:
    path:     /{id}/edit
    defaults: { _controller: "FaucheurBundle:Association:edit" }
    methods:  [GET, POST]

association_delete:
    path:     /{id}/delete
    defaults: { _controller: "FaucheurBundle:Association:delete" }
    methods:  DELETE
