FaucheurBundle\Entity\Action:
    type: entity
    table: action
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 255
        type:
            type: string
            nullable: true
            length: 100
        dateDebut:
            type: datetime
            nullable: true
        duree:
            type: string
            nullable: true
            length: 255
        lieu:
            type: string
            nullable: true
            length: 255
    lifecycleCallbacks: { }
    manyToOne:
        campagne:
            targetEntity: FaucheurBundle\Entity\Campagne