FaucheurBundle\Entity\Aptitude:
    type: entity
    table: aptitude
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        niveau:
            type: integer
            nullable: false
    lifecycleCallbacks: {  }
    oneToMany:
        aptitude:
            targetEntity: FaucheurBundle\Entity\Aptitude
            mappedBy: aptitude