FaucheurBundle\Entity\Association:
    type: entity
    table: association
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 255
        codePostal:
            type: integer
            nullable: true
        type:
            type: string
            nullable: true
            length: 255
    lifecycleCallbacks: {  }