FaucheurBundle\Entity\Competence:
    type: entity
    table: competence
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 255
        detail:
            type: string
            nullable: true
            length: 255
    lifecycleCallbacks: {  }
    oneToOne:
        competenece:
            targetEntity: FaucheurBundle\Entity\Competence
            inversedBy: competence