FaucheurBundle\Entity\Militant:
    type: entity
    table: militant
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: true
            length: 50
        prenom:
            type: string
            nullable: true
            length: 50
        email:
            type: string
            nullable: false
            length: 255
        telephone:
            type: string
            nullable: true
            length: 255
        adresse:
            type: string
            nullable: true
            length: 255
        ville:
            type: string
            nullable: true
            length: 100
        codePostal:
            type: integer
            nullable: true
        facebook:
            type: string
            nullable: true
            length: 255
        twitter:
            type: string
            nullable: true
            length: 255
        notes:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        proximite:
            targetEntity: FaucheurBundle\Entity\Proximite
    manyToMany:
        associations:
            targetEntity: FaucheurBundle\Entity\Association
        aptitude:
            targetEntity: FaucheurBundle\Entity\Aptitude
        formation:
            targetEntity: FaucheurBundle\Entity\Formation
        role:
            targetEntity: FaucheurBundle\Entity\Role