FaucheurBundle\Entity\Proximite:
    type: entity
    table: proximite
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 255
    lifecycleCallbacks: {  }