FaucheurBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: true
            length: 150
    lifecycleCallbacks: {  }
    manyToMany:
        actions:
            targetEntity: FaucheurBundle\Entity\Action
        militants:
            targetEntity: FaucheurBundle\Entity\Militants