<?php

namespace BDDMBundle\Repository;

/**
 * MilitantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilitantRepository extends \Doctrine\ORM\EntityRepository
{
}
